#!/bin/bash
# Test command reference for different test scenarios

echo "Crawl4AI MCP Server - Test Commands"
echo "==================================="
echo ""
echo "Unit Tests Only (no external dependencies):"
echo "  pytest tests/ -v -m 'not integration'"
echo ""
echo "SearXNG Integration Tests Only:"
echo "  pytest tests/ -v -m searxng"
echo ""
echo "All Integration Tests:"
echo "  pytest tests/ -v -m integration"
echo ""
echo "All Tests (unit + integration):"
echo "  pytest tests/ -v"
echo ""
echo "Specific test file:"
echo "  pytest tests/test_searxng_integration.py -v"
echo ""
echo "With coverage report:"
echo "  pytest tests/ -v --cov=src --cov-report=html"
echo ""
echo "Docker Test Environment:"
echo "  Start: docker compose -f docker-compose.test.yml up -d"
echo "  Stop:  docker compose -f docker-compose.test.yml down"
echo "  Logs:  docker compose -f docker-compose.test.yml logs -f"
echo ""